package:
  format-version: "1.1.0"
  name: "touch_host_driver"
  version: "v1.1.0-rc.1"
  type: "api"
  status: "production"
  
  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.19.6"

